- name: Copy Grafana repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install Grafana
  ansible.builtin.dnf:
    name: grafana-enterprise
    state: installed

- name: start Grafana service
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    enabled: yes
    daemon-reload: yes  # we dont give daemon reload here because rpm file is taking care of that
#  when: out.status.ActiveState != "active"

- name: copy file
  ansible.builtin.template:
    src: grafana-expense.json
    dest: /tmp/grafana-expense.json

- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: https://grafana.jyothsnashrey.online
    grafana_api_key: "{{lookup('amazon.aws.aws_ssm', 'grafana.apikey', region='us-east-1') }}"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path:  /tmp/grafana-expense.json
