- name: copy elastic repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed


- name: start Elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes


- name: install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed


- name: start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes