format_version: 10
pipelines:
  grafana-ansible:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/Jyothsnashrey/miscellaneous-code
        shallow_clone: false
        auto_update: true
        branch: main
        includes:
          - src/**/*.*  # if there is only change to this module that never exists this will not auto execute the script
    stages:
    - apply:
        fetch_materials: true
        jobs:
          apply:
            approval:
              type: manual
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments: ["ansible.sh", "grafana"]

